### ISSUE TITLE
Cannot start a notebook

### ISSUE THREAD

**Issue by mgabs** [bramyeni/spark31#1]
I modified the start command for a jupiter notebook to match a local location instead of `/etc/`

```
docker run -it --name spark3 -p 4040-4048:4040-4048 -p 8888-8999:8888-8999 -v /home/mgaber/Workbench/spark31/data:/opt/hdfsvol:rw -v /home/mgaber/Workbench/spark31/etc:/opt/spark/etc:rw spark31
```

Now I get 
```
cp: cannot create regular file '/opt/spark/etc/fairscheduler.xml': Permission denied
cp: cannot create regular file '/opt/spark/etc/log4j.properties': Permission denied
cp: cannot create regular file '/opt/spark/etc/metrics.properties': Permission denied
cp: cannot create regular file '/opt/spark/etc/spark-defaults.conf': Permission denied
cp: cannot create regular file '/opt/spark/etc/spark-env.sh': Permission denied
-bash: line 10: /opt/spark/etc/spark-env.sh: Permission denied
-bash: line 11: /opt/spark/etc/spark-env.sh: Permission denied
-bash: line 12: /opt/spark/etc/spark-env.sh: Permission denied
cp: cannot create regular file '/opt/spark/etc/workers': Permission denied
cp: cannot create directory '/opt/spark/etc/jupyter': Permission denied
```

I tried running as root but no joy
logging into docker I can create delete files from the attached volume

**Comment by bramyeni** [comment]
Hi sorry,

I will have a look later..missed your message

All the mountpoints available right??
Anyway i will get back to you

Cheers

**Comment by mgabs** [comment]
Thanks,
I ended up building an image.

**Comment by bramyeni** [comment]
Hi Mohammed, 

i have been able to reproduce the problem and it seems that i forgot to modify the entrypoint to include chown spark:spark $SPARK_HOME/etc, i have updated the code and it seems worked now!

thanks again for letting me know this

cheers
